spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/mcdonald
    username: postgres
    password: 1234
    platform: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

#server:
#  port: 8081